---
title: "Micro-metrics"
author: "Andrew Dickinson"
date: "<br>`r format(Sys.time(), '%d %B %Y')`"
header-includes:
  - \usepackage{mathtools}
  - \DeclarePairedDelimiter\floor{\lfloor}{\rfloor}
  - \usepackage{amssymb}
output: 
  html_document:
    toc: false
    toc_depth: 3  
    number_sections: false
    theme: flatly
    highlight: tango  
    toc_float:
      collapsed: true
      smooth_scroll: true
runtime: shiny
---

```{r Setup, include = F}
options(htmltools.dir.version = FALSE)
library(pacman)
p_load(broom, wesanderson, ggplot2, ggthemes, viridis, dplyr, magrittr, rddtools,tidyverse, janitor, estimatr, here, broom)# Define pink color
red_pink <- "#e64173"
turquoise <- "#20B2AA"
orange <- "#FFA500"
red <- "#fb6107"
blue <- "#3b3b9a"
green <- "#8bb174"
grey_light <- "grey70"
grey_mid <- "grey50"
grey_dark <- "grey20"
purple <- "#6A5ACD"
slate <- "#314f4f"
# Dark slate grey: #314f4f
# Notes directory
# dir_slides <- "~/Dropbox/Courses/"
# Knitr options
# opts_chunk$set(
#   comment = "#>",
#   fig.align = "center",
#   fig.height = 4,
#   fig.width = 6,
#   # dpi = 300,
#   # cache = T,
#   warning = F,
#   message = F
# )
# A blank theme for ggplot
theme_empty <- theme_bw() + theme(
  line = element_blank(),
  rect = element_blank(),
  strip.text = element_blank(),
  axis.text = element_blank(),
  plot.title = element_blank(),
  axis.title = element_blank(),
  plot.margin = structure(c(0, 0, -1, -1), unit = "lines", valid.unit = 3L, class = "unit"),
  legend.position = "none"
)
theme_simple <- theme_bw() + theme(
  line = element_blank(),
  panel.grid = element_blank(),
  rect = element_blank(),
  axis.text.x = element_text(size = 10),
  axis.text.y = element_text(size = 10),
  axis.ticks = element_blank(),
  plot.title = element_blank(),
  axis.title.x = element_text(angle = 0, vjust = 0.5),
  axis.title.y = element_text(angle = 90, vjust = 0.5),
  legend.position = "none",
  axis.line = element_line(color="black", size = .5)
)
```


```{r}
A <- data.frame(x=c(1,2,3),y=c(3,2,1),z=c(4,5,6),k=c(8,6,7))
B <- data.frame(x=c(1,1,5),y=c(3,5,0),b=c(3,2,4),n=c(9,6,5))

ui <- fluidPage(

selectInput("df", "Select dataframe", choices = c('A'='A','B'='B'), selected = 'A'),
varSelectInput('Y_Axis', label = 'Select variable', data = 'df'),

plotOutput("Plot")

)

server <- shinyServer(function(input, output) {

  df <- reactive({
    x <- get(input$df)
  })

  output$Plot <- renderPlot({
    df <- df()
    plot(x=input$Y_Axis, y=input$Y_Axis)

  })
})

shinyApp(ui = ui, server = server)
```